"""Interfaces que o agente consome. Implementações reais e fakes de teste seguem estas assinaturas."""

from __future__ import annotations

from typing import Protocol

from contracts.models import EnrichedTrack, Intent, PlaylistSummary, ThemePlan, Track


class SpotifyPort(Protocol):
    def me_id(self) -> str: ...
    def my_playlists(self) -> list[PlaylistSummary]: ...
    def playlist_tracks(self, playlist_id: str) -> list[Track]: ...
    def search_tracks(self, query: str, pages: int = 1) -> list[Track]: ...
    def artist_genres(self, artist_id: str) -> list[str]: ...
    def create_playlist(self, name: str, description: str) -> tuple[str, str]: ...
    def replace_items(self, playlist_id: str, uris: list[str]) -> None: ...


class EnricherPort(Protocol):
    def enrich(self, tracks: list[Track]) -> list[EnrichedTrack]: ...


class LLMPort(Protocol):
    def interpret(self, message: str, history: list[tuple[str, str]], playlist_names: list[str]) -> Intent: ...
    def plan_theme(self, theme: str, max_slots: int) -> ThemePlan: ...
